Updated Codes
mkamyab/bitumen_den_vis pull request #2
Opened 2021-11-22 18:15 UTC by gunjanstomar

2021-11-26 18:40 UTC, mkamyab requested changes

2021-11-26 18:40 UTC, mkamyab commented on densitydata.csv
> +IBP,MW,T,P,Density
There is already a `Density.csv` file with exactly the same data in the repository. Delete one of them.
I would also recommend putting the density and viscosity data into a `data` folder rather than under the main repository folder.
The same comment applies to the `viscositydata.csv` file you added in this commit.

2021-11-26 18:40 UTC, mkamyab commented on viscositydata.csv
> +IBP,MW,T,P,Viscosity,Vis
The same comment as the one given for `densitydata.csv` file.

2022-01-19 21:54 UTC, gunjanstomar commented
<ol><li>Can you elaborate this comment "Maybe it is better to display Training vs Testing as subplots for each model". What exactly am I suppose to do? Not plot experimental vs. predicted plot ? </li></ol><p> </p>

---

 <a href='https://app.reviewnb.com/mkamyab/bitumen_den_vis/pull/2/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2022-05-19 19:52 UTC, mkamyab approved these changes

2022-05-19 19:53 UTC, merged